development:
  adapter: postgresql
  encoding: unicode
  database: chess-db
  pool: 5
  username: chess_db_qan4_user
  password: <%=ENV["DB_PASS"] %>
  url: <%=ENV["DATABASE_URL"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: chess-db
  pool: 5
  username: chess_db_qan4_user
  password: <%=ENV["DB_PASS"] %>
  url: <%=ENV["DATABASE_URL"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: chess-db
  pool: 5
  username: chess_db_qan4_user
  password: <%=ENV["DB_PASS"] %>
  url: <%=ENV["DATABASE_URL"] %>